name: Guardar Resultado Tres en Raya

on:
  push:
  workflow_dispatch:

jobs:
  build-tres-en-raya:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ir a la carpeta del proyecto
        run: cd SecondMidterm_Exam/class17/tres-en-raya && pwd

      - name: Instalar dependencias
        run: npm ci
        working-directory: SecondMidterm_Exam/class17/tres-en-raya

      - name: Verificar version de Node
        run: node --version

      - name: Verificar version de npm
        run: npm --version

      - name: Lint del proyecto
        run: npm run lint
        working-directory: SecondMidterm_Exam/class17/tres-en-raya

      - name: Build del proyecto
        run: npm run build
        working-directory: SecondMidterm_Exam/class17/tres-en-raya

      - name: Guardar resultado del build
        uses: actions/upload-artifact@v4
        with:
          name: tres-en-raya-build
          path: SecondMidterm_Exam/class17/tres-en-raya/dist
      - name: Guardar ZIP
        uses: actions/upload-artifact@v4
        with:
          name: aplicacion-web
          path: 2doParcial/Class17/tres-en-raya/dist